### ISSUE TITLE
Installs into "include/include"

### ISSUE THREAD

**Issue by eschnett** [agenium-scale/nsimd#22] opened 2019-10-24 13:39 UTC
I just installed nsimd (master branch) on OS X, and the include files ended up in `$INSTALLDIR/include/include/nsimd`. Note the double `include/include` that probably shouldn't be there.

**Comment by ccharly** [comment] 2019-10-24 13:48
Indeed. I'm fixing this. Thanks for the report.

**Comment by ccharly** [comment] 2019-10-24 13:50
Should be fixed by now. I've already merged the PR. Could you try it again and confirm that it's working as intended? I'll close right after. Thanks.

**Comment by eschnett** [comment] 2019-10-24 15:50
Confirmed; it's fine now.

**Closed as completed** 2019-10-24 16:12 UTC
